# Controls when the action will run. 
# WARNING: May have security issues with Firebase with error 
# Firestore (9.14.0): Could not reach Cloud Firestore backend. Connection failed 1 times.
# Most recent error: FirebaseError: [code=permission-denied]: Permission denied: Consumer 'project:undefined' has been suspended.
# This typically indicates that your device does not have a healthy Internet connection at the moment. 
# The client will operate in offline mode until it is able to successfully connect to the backend
on:
 push:
 pull_request:
  branches: master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    - name: 🗑️ Removing assests folder
      uses: fifsky/ssh-action@master
      with:
       command: |
        cd /var/www/html/ryukyu.pro/
        rm -r assets 
       host: ${{ secrets.HOST }}
       user: ${{ secrets.USER }}
       pass: ${{ secrets.PASSWORD }}
       args: "-tt"
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        local_path: "./dist/*"
        remote_path: "/var/www/html/ryukyu.pro/"
