# Controls when the action will run. 
on:
 push:
 pull_request:
  branches: master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    - name: 🗑️ Removing assests folder
      uses: fifsky/ssh-action@master
      with:
       command: |
        cd /var/www/html/ryukyu.pro/
        rm -r assets 
       host: ${{ secrets.HOST }}
       user: ${{ secrets.USER }}
       pass: ${{ secrets.PASSWORD }}
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        local_path: "./dist/*"
        remote_path: "/var/www/html/ryukyu.pro/"
